#!/bin/bash
if [ -z "$1" ]; then
  echo " "
  echo "Debe ingresar el nombre de la clase de prueba"
  echo "  "
  echo "Ejemplo:"
  echo "  ./runtest DriverTest"
  exit 1
fi

if ! find . -type f -name "$1.java" | grep -e ".*/test/.*/$1.java"; then
    echo -e "\e[31m"
    echo "ERROR: El archivo $1.java no se encontró en ./src/test/java/**/*"
    echo -e "\e[39m"
    exit 1
fi

if echo "$1" | grep -e "RepositoryTest" > /dev/null; then
    echo " "
    echo -e "\e[33m"
    echo "Advertencia: Se va a ejecutar un Test Container, asegurate que Docker esté corriendo"
    read -p "¿Deseas continuar? (s/n): " -n 1 -r
    echo " "
    if [[ ! $REPLY =~ ^[Ss]$ ]]; then
        echo -e "\e[39m"
        echo " "
        exit 1
    fi
    echo -e "\e[39m"
    echo " "
fi

./mvnw clean test "-P$1"
