name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: DriverControllerIntegrationTest
        id: drivercontrollerintegrationtest
        uses: education/autograding-command-grader@v1
        with:
          test-name: DriverControllerIntegrationTest
          setup-command: mvn compile
          command: mvn clean test -PDriverControllerIntegrationTest
          timeout: 10
          max-score: 2

      - name: PassengerControllerIntegrationTest
        id: passengercontrollerintegrationtest
        uses: education/autograding-command-grader@v1
        with:
          test-name: PassengerControllerIntegrationTest
          setup-command: mvn compile
          command: mvn clean test -PPassengerControllerIntegrationTest
          timeout: 10
          max-score: 2

      - name: ReviewControllerIntegrationTest
        id: reviewcontrollerintegrationtest
        uses: education/autograding-command-grader@v1
        with:
          test-name: ReviewControllerIntegrationTest
          setup-command: mvn compile
          command: mvn clean test -PReviewControllerIntegrationTest
          timeout: 10
          max-score: 2

      - name: RideControllerIntegrationTest
        id: ridecontrollerintegrationtest
        uses: education/autograding-command-grader@v1
        with:
          test-name: RideControllerIntegrationTest
          setup-command: mvn compile
          command: mvn clean test -PRideControllerIntegrationTest
          timeout: 10
          max-score: 2

      - name: VehicleTest
        id: vehicletest
        uses: education/autograding-command-grader@v1
        with:
          test-name: VehicleTest
          setup-command: mvn compile
          command: mvn clean test -PVehicleTest
          timeout: 10
          max-score: 1

      - name: DriverTest
        id: drivertest
        uses: education/autograding-command-grader@v1
        with:
          test-name: DriverTest
          setup-command: mvn compile
          command: mvn clean test -PDriverTest
          timeout: 10
          max-score: 1

      - name: PassengerTest
        id: passengertest
        uses: education/autograding-command-grader@v1
        with:
          test-name: PassengerTest
          setup-command: mvn compile
          command: mvn clean test -PPassengerTest
          timeout: 10
          max-score: 1

      - name: ReviewTest
        id: reviewtest
        uses: education/autograding-command-grader@v1
        with:
          test-name: ReviewTest
          setup-command: mvn compile
          command: mvn clean test -PReviewTest
          timeout: 10
          max-score: 1

      - name: RideTest
        id: ridetest
        uses: education/autograding-command-grader@v1
        with:
          test-name: RideTest
          setup-command: mvn compile
          command: mvn clean test -PRideTest
          timeout: 10
          max-score: 1

      - name: AbstractContainerBaseTest
        id: abstractcontainerbasetest
        uses: education/autograding-command-grader@v1
        with:
          test-name: AbstractContainerBaseTest
          setup-command: mvn compile
          command: mvn clean test -PAbstractContainerBaseTest
          timeout: 10
          max-score: 0

      - name: DriverRepositoryTest
        id: driverrepositorytest
        uses: education/autograding-command-grader@v1
        with:
          test-name: DriverRepositoryTest
          setup-command: mvn compile
          command: mvn clean test -PDriverRepositoryTest
          timeout: 10
          max-score: 2

      - name: PassengerRepositoryTest
        id: passengerrepositorytest
        uses: education/autograding-command-grader@v1
        with:
          test-name: PassengerRepositoryTest
          setup-command: mvn compile
          command: mvn clean test -PPassengerRepositoryTest
          timeout: 10
          max-score: 2

      - name: ReviewRepositoryTest
        id: reviewrepositorytest
        uses: education/autograding-command-grader@v1
        with:
          test-name: ReviewRepositoryTest
          setup-command: mvn compile
          command: mvn clean test -PReviewRepositoryTest
          timeout: 10
          max-score: 2

      - name: RideRepositoryTest
        id: riderepositorytest
        uses: education/autograding-command-grader@v1
        with:
          test-name: RideRepositoryTest
          setup-command: mvn compile
          command: mvn clean test -PRideRepositoryTest
          timeout: 10
          max-score: 2

      - name: VehicleRepositoryTest
        id: vehiclerepositorytest
        uses: education/autograding-command-grader@v1
        with:
          test-name: VehicleRepositoryTest
          setup-command: mvn compile
          command: mvn clean test -PVehicleRepositoryTest
          timeout: 10
          max-score: 2

      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          DRIVERCONTROLLERINTEGRATIONTEST_RESULTS: "${{steps.drivercontrollerintegrationtest.outputs.result}}"
          PASSENGERCONTROLLERINTEGRATIONTEST_RESULTS: "${{steps.passengercontrollerintegrationtest.outputs.result}}"
          REVIEWCONTROLLERINTEGRATIONTEST_RESULTS: "${{steps.reviewcontrollerintegrationtest.outputs.result}}"
          RIDECONTROLLERINTEGRATIONTEST_RESULTS: "${{steps.ridecontrollerintegrationtest.outputs.result}}"
          VEHICLETEST_RESULTS: "${{steps.vehicletest.outputs.result}}"
          DRIVERTEST_RESULTS: "${{steps.drivertest.outputs.result}}"
          PASSENGERTEST_RESULTS: "${{steps.passengertest.outputs.result}}"
          REVIEWTEST_RESULTS: "${{steps.reviewtest.outputs.result}}"
          RIDETEST_RESULTS: "${{steps.ridetest.outputs.result}}"
          ABSTRACTCONTAINERBASETEST_RESULTS: "${{steps.abstractcontainerbasetest.outputs.result}}"
          DRIVERREPOSITORYTEST_RESULTS: "${{steps.driverrepositorytest.outputs.result}}"
          PASSENGERREPOSITORYTEST_RESULTS: "${{steps.passengerrepositorytest.outputs.result}}"
          REVIEWREPOSITORYTEST_RESULTS: "${{steps.reviewrepositorytest.outputs.result}}"
          RIDEREPOSITORYTEST_RESULTS: "${{steps.riderepositorytest.outputs.result}}"
          VEHICLEREPOSITORYTEST_RESULTS: "${{steps.vehiclerepositorytest.outputs.result}}"
        with:
          runners: drivercontrollerintegrationtest,passengercontrollerintegrationtest,reviewcontrollerintegrationtest,ridecontrollerintegrationtest,vehicletest,drivertest,passengertest,reviewtest,ridetest,abstractcontainerbasetest,driverrepositorytest,passengerrepositorytest,reviewrepositorytest,riderepositorytest,vehiclerepositorytest
